use std::fmt::Write;

use wgsl_to_wgpu::{MatrixVectorTypes, Module, ModulePath, TypePath, WriteOptions};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut root = Module::default();

    let options = WriteOptions {
        derive_bytemuck_vertex: true,
        derive_encase_host_shareable: true,
        matrix_vector_types: MatrixVectorTypes::Glam,
        rustfmt: true,
        validate: Some(Default::default()),
        named_bind_groups: true,
        shared_bind_groups: true,
        ..Default::default()
    };

    for name in ["shader", "shader_triangle", "compute_shader"] {
        println!("cargo:rerun-if-changed=src/{name}.wgsl");
        let wgsl_file = format!("src/{name}.wgsl");
        let wgsl_source = std::fs::read_to_string(&wgsl_file)?;

        // Generate the Rust bindings and write to a file.
        let mut text = String::new();
        writeln!(&mut text, "// File automatically generated by build.rs.")?;
        writeln!(&mut text, "// Changes made to this file will not be saved.")?;

        root.add_shader_module(
            &wgsl_source,
            Some(&format!("{name}.wgsl")),
            options,
            ModulePath {
                components: vec![name.to_string()],
            },
            // demangle with double underscore to separate parts
            |name| {
                let mut parts = name
                    .split("__")
                    .map(|part| part.to_string())
                    .collect::<Vec<_>>();
                TypePath {
                    name: parts.pop().expect("name are not empty"),
                    parent: ModulePath { components: parts },
                }
            },
        )
        .inspect_err(|error| error.emit_to_stderr_with_path(&wgsl_source, &wgsl_file))
        .map_err(|_| "Failed to validate shader")?;
    }

    let text = root.to_generated_bindings(options);
    std::fs::write("src/shader_bindings.rs", text.as_bytes())?;

    Ok(())
}
