[package]
name = "example"
version = "0.19.0"
edition.workspace = true
publish = false

[dependencies]
winit = "0.30"
wgpu.workspace = true
futures = "0.3"
bytemuck = { workspace = true, features = ["derive"] }
encase.workspace = true
glam = { workspace = true, features = ["bytemuck", "encase"] }

[build-dependencies]
wgsl_to_wgpu = { path = "../wgsl_to_wgpu" }
