[workspace]
# wgpu requires the newer resolver
resolver = "2"
members = ["wgsl_to_wgpu", "example", "wgsl_to_wgpu/test_compile"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
wgpu = "30.0"
wgpu-types = "30.0"
naga = "30.0"
glam = "0.33.2"
encase = "0.12"
bytemuck = "1.25"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
