[package]
name = "test_compile"
version = "0.18.0"
edition.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
encase.workspace = true
glam.workspace = true
half = { version = "2.7", features = ["bytemuck"] }
nalgebra = "0.34"
serde = { version = "1.0", features = ["derive"] }
wgpu.workspace = true
trybuild = "1.0"
